# Chain
genesis-file="genesis.json"

# Mining
miner-enabled=true
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"

# Network
rpc-http-enabled=true
rpc-http-apis=["ETH", "NET", "WEB3", "MINER"]
rpc-http-cors-origins=["all"]
host-allowlist=["all"]

# Set JSON-RPC configurations
rpc-http-host="localhost"
rpc-http-port="4989"

# Data
data-path="besu-data"

# Minimum gas price to zero
min-gas-price=0
